excluded:
    - ProjectManager/Resources/AppDelegate.swift
    - ProjectManager/Resources/SceneDelegate.swift
    
disabled_rules:
    - trailing_whitespace

opt_in_rules:
    - force_unwrapping
    
force_unwrapping: error
